# Generated by Django 5.1.2 on 2024-10-18 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IOT',
            fields=[
                ('iot', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='PollutionEstimate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('avg_co', models.FloatField()),
                ('avg_no2', models.FloatField()),
                ('avg_so2', models.FloatField()),
                ('avg_co2', models.FloatField()),
                ('avg_ch4', models.FloatField()),
                ('avg_benzene', models.FloatField()),
                ('avg_nh3', models.FloatField()),
                ('finalEstimate', models.FloatField()),
                ('iot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.iot')),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('co', models.FloatField()),
                ('no2', models.FloatField()),
                ('so2', models.FloatField()),
                ('co2', models.FloatField()),
                ('ch4', models.FloatField()),
                ('benzene', models.FloatField()),
                ('nh3', models.FloatField()),
                ('nox', models.FloatField()),
                ('iot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.iot')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('number_plate', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='iot',
            name='number_plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicle'),
        ),
    ]
