# Generated by Django 5.1.2 on 2025-02-19 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rtouser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RTOUser',
        ),
    ]
