# Generated by Django 5.1.2 on 2025-03-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_rtouser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollutionestimate',
            old_name='avg_benzene',
            new_name='avg_pm',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='benzene',
            new_name='pm',
        ),
        migrations.RemoveField(
            model_name='pollutionestimate',
            name='avg_ch4',
        ),
        migrations.RemoveField(
            model_name='pollutionestimate',
            name='avg_nh3',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='ch4',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='nh3',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='nox',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='FuelType',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel')], default='Petrol', max_length=6),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Vehicle_type',
            field=models.CharField(choices=[('2W', '2W'), ('4W', '4W'), ('HDV', 'Heavy Duty Vehicle')], default='2W', max_length=20),
        ),
    ]
