# Generated by Django 5.1.2 on 2025-03-10 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_avg_benzene_pollutionestimate_avg_pm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('paid', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('iot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.iot')),
            ],
        ),
    ]
