# Generated by Django 5.1.2 on 2025-04-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_challan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='pm',
        ),
    ]
