# Generated by Django 5.1.2 on 2025-04-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_sensordata_pm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollutionestimate',
            name='avg_pm',
        ),
    ]
